public class ContohVariabel08 {
    public static void main(String[] args) {
        String salahSatuHobySayaAdalah = "Bermain petak umpet";
boolean isPandai = true;
char jenisKelamin = 'P';
byte umurSayaSekarang = 18;
double ipk = 4.00, tinggi = 1.55;
System.out.println(salahSatuHobySayaAdalah);
System.out.println("Apakah pandai? " + isPandai);
System.out.println("Jenis kelamin: " + jenisKelamin);
System.out.println("Umurku saat ini: " + _umurSayaSekarang);
System.out.println(String.format("Saya beripk %S, dengan tinggi badan %S", $ipk, tinggi));
    }
}